name: CI for Angular

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Generate coverage report
        run: npm run test:coverage -- --browsers=ChromeHeadless

      - name: Debug - List coverage directory
        run: ls -la coverage/

      - name: Check coverage file path
        run: find . -name "lcov.info"

      - name: SonarCloud Analysis
        run: >
          npx sonar-scanner
          -Dsonar.projectKey=alvaroavilesr_Alvaro_Aviles_Redondo_TFM_Angular
          -Dsonar.organization=alvaroavilesr
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=src
          -Dsonar.tests=src
          -Dsonar.test.inclusions=src/**/*.spec.ts
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.exclusions=**/*.html,**/*.css,**/*.routes.ts
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
